./checker couple1
./checker couple2
./checker couple3
./checker couple4
./checker couple5
./checker couple6
./checker couple7
./checker couple8
./checker couple9
./checker couple10
./checker couple11
./checker couple12
./checker couple13
./checker couple14
./checker couple15
./checker couple16
./checker couple17
./checker couple18
./checker couple19
./checker couple20
./checker couple21
./checker couple22
./checker couple23
./checker couple24
./checker couple25
./checker couple26
./checker couple27
./checker couple28
./checker couple29
./checker couple30
./checker couple31
./checker couple32
./checker couple33
./checker couple34
./checker couple35
./checker couple36
./checker couple37
./checker couple38
./checker couple39
./checker couple40
