./fit < couple1.txt > couple1.out
./fit < couple2.txt > couple2.out
./fit < couple3.txt > couple3.out
./fit < couple4.txt > couple4.out
./fit < couple5.txt > couple5.out
./fit < couple6.txt > couple6.out
./fit < couple7.txt > couple7.out
./fit < couple8.txt > couple8.out
./fit < couple9.txt > couple9.out
./fit < couple10.txt > couple10.out
./fit < couple11.txt > couple11.out
./fit < couple12.txt > couple12.out
./fit < couple13.txt > couple13.out
./fit < couple14.txt > couple14.out
./fit < couple15.txt > couple15.out
./fit < couple16.txt > couple16.out
./fit < couple17.txt > couple17.out
./fit < couple18.txt > couple18.out
./fit < couple19.txt > couple19.out
./fit < couple20.txt > couple20.out
./fit < couple21.txt > couple21.out
./fit < couple22.txt > couple22.out
./fit < couple23.txt > couple23.out
./fit < couple24.txt > couple24.out
./fit < couple25.txt > couple25.out
./fit < couple26.txt > couple26.out
./fit < couple27.txt > couple27.out
./fit < couple28.txt > couple28.out
./fit < couple29.txt > couple29.out
./fit < couple30.txt > couple30.out
